os: Visual Studio 2015
platform: x64
before_build:
  - pip install numpy pyinstaller tabulate
  - md build
  - cd build
# note: boost is not available for vs 2017 currently
  - set BOOST_INCLUDEDIR=C:\Libraries\boost_1_63_0
  - set BOOST_LIBRARYDIR=C:\Libraries\boost_1_63_0\lib64-msvc-14.0
  - cmake -G "Visual Studio 14 Win64" -DBUILD_ALL=1 ..
