language: c++
dist: trusty
sudo: required
before_install:
  - sudo apt-get install libboost-dev
cache:
  directories:
    - build
script:
  - mkdir -p build && cd build
  - cmake --version
  - cmake ..
  - make
  - sudo make install


