language: c++
dist: trusty
sudo: required
before_install:
  - sudo apt-get install libboost-dev
install:
  - pip install numpy
cache:
  directories:
    - build
script:
  - mkdir -p build && cd build
# note: you might need to clear the cache (https://travis-ci.org/Reaktoro/Reaktoro/caches)
#  when you make changes to the cmake configuration
  - cmake .. -DBUILD_ALL=1
  - make
  - make test
  - sudo make install


