name: C/C++ CI

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
      
    - name: Setting up conda
      shell: bash
      run: |
        conda_install.sh
        export "CFLAGS=-I$CONDA_PREFIX/include $CFLAGS"
        export "CXXFLAGS=-I$CONDA_PREFIX/include $CXXFLAGS"
        echo -e "\n\nCurrent compiler configuration:\nCXX=$CXX\nCC=$CC\nCFLAGS=$CFLAGS\nCXXFLAGS=$CXXFLAGS"
        echo -e "\nCurrent packages:"
        $CONDA list
      
    - name: Create Build Directory
      working-directory: ${{runner.workspace}}
      shell: bash
      run: mkdir build
    
    - name: Configure CMake
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: |
        inv -e compile -n $NUMBER_OF_COMPILATION_JOBS
        python ci/check_compiled_files.py
        pytest -n auto -ra -vv .
