name: C/C++ CI

on: [push]

env:
  BUILD_TYPE: Release
  PY_VER: 3.7

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macOS-latest]
    
    steps:
    - uses: actions/checkout@v1
      
    - name: Setting up conda
      shell: python
      run: conda install
      
    - name: Create Build Directory
      working-directory: ${{runner.workspace}}
      shell: bash
      run: mkdir build
    
    - name: Configure CMake
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE
    
    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: python
      run: cmake --build . --config $BUILD_TYPE

    - name: Test
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: ctest -C $BUILD_TYPE
